sudo: required
language: python
os: linux
dist: xenial
python:
 - "3.6"
 - "3.7"
 - "3.8"
env:
# See, https://docs.travis-ci.com/user/speeding-up-the-build/
# We need a balanced distribution of the tests
# Once we add and remove tests, this distribution may become unbalanced.
# Feel free to move tests around to make the running time of the jobs
# as close as possible.
  - TESTS=test_[a-b,d-e]*
# test_crawl.py is the longest running test.
  - TESTS=test_c*
  - TESTS=test_[f-h]*
  - TESTS=test_[i-z]*
git:
  depth: 3
before_install:
  - "export DISPLAY=:99.0"
  - "export BOTO_CONFIG=/dev/null" # https://github.com/travis-ci/travis-ci/issues/7940
install:
  - echo "y" | ./install.sh
  - pip3 install --upgrade -r requirements.txt -r requirements-dev.txt
before_script:
  - flake8
script:
  - cd test
  - python3 -m pytest -s -v --durations=10 $TESTS

jobs:
  include:
    - language:
      python:
      env:
        - TESTS="Docker"
      services:
        - docker
      before_install:
      before_script:
      install:
      script:
        - docker build -f Dockerfile -t openwpm .
        - ./.deploy-to-dockerhub.sh
    - language: node_js
      python:
      env:
        - TESTS="webext-instrumentation-node-8"
      before_install:
      - cd automation/Extension/webext-instrumentation
      before_script:
      install:
        - npm install
      script:
        - npm test
      sudo: false
      node_js: "8"
      # keep the npm cache to speed up installs
      cache:
        directories:
        - "$HOME/.npm"
      after_success:
        - # npx nyc report --reporter=lcov | npx codecov
        - npm run cov:check
    # jobs defined in jobs.include does not automatically expand,
    # so instead of being able to supply an extra entry to "node_js",
    # we need to duplicate the above entry below with new values
    # for "node_js"
    - language: node_js
      python:
      env:
        - TESTS="webext-instrumentation-node-10"
      before_install:
      - cd automation/Extension/webext-instrumentation
      before_script:
      install:
        - npm install
      script:
        - npm test
      sudo: false
      node_js: "10"
      # keep the npm cache to speed up installs
      cache:
        directories:
        - "$HOME/.npm"
      after_success:
        - # npx nyc report --reporter=lcov | npx codecov
        - npm run cov:check
    - language: node_js
      python:
      env:
        - TESTS="webext-instrumentation-node-12"
      before_install:
      - cd automation/Extension/webext-instrumentation
      before_script:
      install:
        - npm install
      script:
        - npm test
      sudo: false
      node_js: "12"
      # keep the npm cache to speed up installs
      cache:
        directories:
        - "$HOME/.npm"
      after_success:
        - # npx nyc report --reporter=lcov | npx codecov
        - npm run cov:check
