channels:
- conda-forge
- main
dependencies:
- beautifulsoup4=4.10.0
- black=22.1.0
- click=8.0.4
- codecov=2.1.11
- dill=0.3.4
- gcsfs=2022.2.0
- geckodriver=0.30.0
- ipython=8.1.1
- isort=5.10.1
- leveldb=1.23
- mamba=0.22.1
- multiprocess=0.70.12.2
- mypy=0.941
- nodejs=14.18.3
- pandas=1.4.1
- pillow=9.0.1
- pip=22.0.4
- pre-commit=2.17.0
- psutil=5.9.0
- pyarrow=7.0.0
- pytest-asyncio=0.18.2
- pytest-cov=3.0.0
- pytest=7.1.1
- python=3.10.2
- pyvirtualdisplay=3.0
- recommonmark=0.7.1
- redis-py=4.1.4
- s3fs=2022.2.0
- selenium=4.1.0
- sentry-sdk=1.5.8
- sphinx-markdown-tables=0.0.15
- sphinx=4.4.0
- tabulate=0.8.9
- tblib=1.7.0
- wget=1.20.3
- pip:
  - dataclasses-json==0.5.7
  - domain-utils==0.7.1
  - jsonschema==4.4.0
  - plyvel==1.4.0
  - types-pyyaml==6.0.5
  - types-redis==4.1.18
  - types-tabulate==0.8.6
name: openwpm
