channels:
- conda-forge
dependencies:
- beautifulsoup4=4.14.3
- black=26.1.0
- click=8.3.1
- dill=0.4.1
- easyprocess=1.1
- gcsfs=2026.2.0
- geckodriver=0.36.0
- ipython=9.10.0
- isort=8.0.0
- leveldb=1.23
- multiprocess=0.70.19
- mypy=1.19.1
- nodejs=25.6.1
- pandas=3.0.1
- pillow=12.1.1
- pip=26.0.1
- plyvel=1.5.1
- pre-commit=4.5.1
- psutil=7.2.2
- pyarrow=23.0.1
- pytest-asyncio=1.3.0
- pytest-cov=7.0.0
- pytest=9.0.2
- python=3.12.12
- pyvirtualdisplay=3.0
- recommonmark=0.7.1
- redis-py=7.2.0
- s3fs=2026.2.0
- selenium=4.41.0
- sentry-sdk=2.53.0
- sphinx-markdown-tables=0.0.17
- sphinx=9.1.0
- tabulate=0.9.0
- tblib=3.2.2
- wget=1.25.0
- pip:
  - dataclasses-json==0.6.7
  - domain-utils==0.7.1
  - jsonschema==4.26.0
  - tranco==0.8.1
  - types-pyyaml==6.0.12.20250915
  - types-redis==4.6.0.20241004
  - types-tabulate==0.9.0.20241207
name: openwpm
