channels:
- conda-forge
- main
dependencies:
- beautifulsoup4=4.12.2
- black=23.3.0
- click=8.1.3
- codecov=2.1.13
- dill=0.3.6
- easyprocess=1.1
- gcsfs=2023.6.0
- geckodriver=0.33.0
- ipython=8.14.0
- isort=5.12.0
- leveldb=1.23
- multiprocess=0.70.14
- mypy=1.3.0
- nodejs=18.15.0
- pandas=2.0.2
- pillow=9.5.0
- pip=23.1.2
- pre-commit=3.3.3
- psutil=5.9.5
- pyarrow=12.0.0
- pytest-asyncio=0.21.0
- pytest-cov=4.1.0
- pytest=7.3.2
- python=3.11.4
- pyvirtualdisplay=3.0
- recommonmark=0.7.1
- redis-py=4.5.5
- s3fs=2023.6.0
- selenium=4.10.0
- sentry-sdk=1.21.1
- sphinx-markdown-tables=0.0.17
- sphinx=7.0.1
- tabulate=0.9.0
- tblib=1.7.0
- wget=1.20.3
- pip:
  - dataclasses-json==0.5.8
  - domain-utils==0.7.1
  - jsonschema==4.17.3
  - plyvel==1.5.0
  - tranco==0.6
  - types-pyyaml==6.0.12.3
  - types-redis==4.4.0.2
  - types-tabulate==0.9.0.0
name: openwpm
