channels:
- conda-forge
- main
dependencies:
- autopep8=1.5.4
- beautifulsoup4=4.9.3
- click=7.1.2
- codecov=2.1.9
- dill=0.3.2
- flake8-isort=4.0.0
- flake8=3.8.4
- geckodriver=0.26.0
- ipython=7.18.1
- leveldb=1.22
- localstack=0.11.1.1
- multiprocess=0.70.10
- nodejs=14.13.0
- pandas=1.1.3
- pillow=7.2.0
- pip=20.2.3
- pre-commit=2.7.1
- psutil=5.7.2
- pyarrow=1.0.1
- pytest-cov=2.10.1
- pytest=6.1.1
- python=3.8.5
- pyvirtualdisplay=0.2.5
- redis-py=3.5.3
- s3fs=0.4.0
- selenium=3.141.0
- sentry-sdk=0.18.0
- tabulate=0.8.7
- tblib=1.6.0
- wget=1.20.1
- pip:
  - amazon-kclpy==2.0.1
  - crontab==0.22.9
  - domain-utils==0.7.1
  - flask-cors==3.0.9
  - jsonschema==3.2.0
  - moto-ext==1.3.15.15
  - plyvel==1.2.0
  - subprocess32==3.5.4
name: openwpm
