channels:
- conda-forge
dependencies:
- beautifulsoup4=4.12.3
- black=24.10.0
- click=8.1.8
- dill=0.3.9
- easyprocess=1.1
- gcsfs=2024.12.0
- geckodriver=0.35.0
- ipython=8.31.0
- isort=5.13.2
- leveldb=1.23
- multiprocess=0.70.17
- mypy=1.14.1
- nodejs=22.12.0
- pandas=2.2.3
- pillow=11.1.0
- pip=24.3.1
- plyvel=1.5.1
- pre-commit=4.0.1
- psutil=6.1.1
- pyarrow=18.1.0
- pytest-asyncio=0.25.2
- pytest-cov=6.0.0
- pytest=8.3.4
- python=3.12.8
- pyvirtualdisplay=2.2
- recommonmark=0.7.1
- redis-py=5.2.1
- s3fs=2024.12.0
- selenium=4.27.1
- sentry-sdk=2.20.0
- sphinx-markdown-tables=0.0.17
- sphinx=8.1.3
- tabulate=0.9.0
- tblib=3.0.0
- wget=1.21.4
- pip:
  - dataclasses-json==0.6.7
  - domain-utils==0.7.1
  - jsonschema==4.23.0
  - tranco==0.8.1
  - types-pyyaml==6.0.12.20241230
  - types-redis==4.6.0.20241004
  - types-tabulate==0.9.0.20241207
name: openwpm
