channels:
- conda-forge
- main
dependencies:
- beautifulsoup4=4.10.0
- black=21.11b1
- click=8.0.3
- codecov=2.1.11
- dill=0.3.4
- gcsfs=2021.11.1
- geckodriver=0.30.0
- ipython=7.30.1
- isort=5.10.1
- leveldb=1.23
- multiprocess=0.70.12.2
- mypy=0.910
- nodejs=14.17.4
- pandas=1.3.4
- pillow=8.4.0
- pip=21.3.1
- pre-commit=2.16.0
- psutil=5.8.0
- pyarrow=6.0.1
- pytest-asyncio=0.16.0
- pytest-cov=3.0.0
- pytest=6.2.5
- python=3.9.7
- pyvirtualdisplay=2.2
- recommonmark=0.7.1
- redis-py=4.0.2
- s3fs=2021.11.1
- selenium=3.141.0
- sentry-sdk=1.5.0
- sphinx-markdown-tables=0.0.15
- sphinx=4.3.1
- tabulate=0.8.9
- tblib=1.7.0
- wget=1.20.3
- pip:
  - dataclasses-json==0.5.6
  - domain-utils==0.7.1
  - jsonschema==4.2.1
  - plyvel==1.3.0
  - types-pyyaml==6.0.1
  - types-redis==4.0.3
  - types-tabulate==0.8.3
name: openwpm
