channels:
    - conda-forge
dependencies:
    - autopep8
    - flake8
    - flake8-isort
    - ipython
    - localstack
    - pip
    - pre-commit
    - pytest
    - pip:
        # Select depenedencies from localstack[full] that we need
        - amazon-kclpy
        - crontab
        - flask-cors
        - moto-ext
        - subprocess32
