channels:
- conda-forge
- main
dependencies:
- beautifulsoup4=4.9.3
- black=21.7b0
- click=8.0.1
- codecov=2.1.11
- dill=0.3.4
- gcsfs=2021.7.0
- geckodriver=0.29.0
- ipython=7.25.0
- leveldb=1.23
- multiprocess=0.70.12.2
- mypy=0.910
- nodejs=14.17.1
- pandas=1.3.0
- pillow=8.3.1
- pip=21.1.3
- pre-commit=2.13.0
- psutil=5.8.0
- pyarrow=4.0.1
- pytest-asyncio=0.15.1
- pytest-cov=2.12.1
- pytest=6.2.4
- python=3.9.6
- pyvirtualdisplay=2.2
- recommonmark=0.7.1
- redis-py=3.5.3
- s3fs=2021.7.0
- selenium=3.141.0
- sentry-sdk=1.3.0
- sphinx-markdown-tables=0.0.15
- sphinx=4.1.1
- tabulate=0.8.9
- tblib=1.7.0
- wget=1.20.3
- pip:
  - dataclasses-json==0.5.4
  - domain-utils==0.7.1
  - jsonschema==3.2.0
  - plyvel==1.3.0
  - types-pyyaml==5.4.3
  - types-redis==3.5.4
  - types-tabulate==0.1.1
name: openwpm
