channels:
- conda-forge
- main
dependencies:
- beautifulsoup4=4.11.1
- black=22.3.0
- click=8.1.3
- codecov=2.1.11
- dill=0.3.4
- easyprocess=1.1
- gcsfs=2022.3.0
- geckodriver=0.30.0
- ipython=8.3.0
- isort=5.10.1
- leveldb=1.23
- multiprocess=0.70.12.2
- mypy=0.942
- nodejs=14.18.3
- pandas=1.4.2
- pillow=9.1.0
- pip=22.0.4
- pre-commit=2.18.1
- psutil=5.9.0
- pyarrow=7.0.0
- pytest-asyncio=0.18.3
- pytest-cov=3.0.0
- pytest=7.1.2
- python=3.10.4
- pyvirtualdisplay=3.0
- recommonmark=0.7.1
- redis-py=4.2.2
- s3fs=2022.3.0
- selenium=4.1.0
- sentry-sdk=1.5.11
- sphinx-markdown-tables=0.0.15
- sphinx=4.5.0
- tabulate=0.8.9
- tblib=1.7.0
- wget=1.20.3
- pip:
  - dataclasses-json==0.5.7
  - domain-utils==0.7.1
  - jsonschema==4.4.0
  - plyvel==1.4.0
  - types-pyyaml==6.0.7
  - types-redis==4.2.1
  - types-tabulate==0.8.8
name: openwpm
