channels:
- conda-forge
- main
dependencies:
- autopep8=1.5.2
- beautifulsoup4=4.9.0
- dill=0.3.1.1
- flake8-isort=3.0.0
- flake8=3.8.1
- geckodriver=0.26.0
- ipython=7.14.0
- leveldb=1.22
- localstack=0.11.1.1
- multiprocess=0.70.9
- nodejs=13.13.0
- pandas=1.0.3
- pillow=7.1.2
- pip=20.1
- pre-commit=2.4.0
- psutil=5.7.0
- pyarrow=0.17.0
- pytest=5.4.2
- python=3.8.2
- pyvirtualdisplay=0.2.5
- redis-py=3.5.1
- s3fs=0.4.0
- selenium=3.141.0
- sentry-sdk=0.14.4
- tabulate=0.8.7
- tblib=1.6.0
- wget=1.20.1
- xorg-x11-server-xvfb-cos6-x86_64=1.17.4
- pip:
  - crontab==0.22.6
  - domain-utils==0.7.1
  - flask-cors==3.0.8
  - moto-ext==1.3.15.15
  - plyvel==1.2.0
  - subprocess32==3.5.4
name: openwpm
