channels:
- conda-forge
- main
dependencies:
- beautifulsoup4=4.9.3
- black=20.8b1
- click=7.1.2
- codecov=2.1.11
- dill=0.3.3
- gcsfs=0.7.2
- geckodriver=0.29.0
- ipython=7.20.0
- leveldb=1.22
- multiprocess=0.70.11.1
- mypy=0.812
- nodejs=14.15.1
- pandas=1.2.2
- pillow=8.1.0
- pip=21.0.1
- pre-commit=2.10.1
- psutil=5.8.0
- pyarrow=3.0.0
- pytest-asyncio=0.14.0
- pytest-cov=2.11.1
- pytest=6.2.2
- python=3.9.2
- pyvirtualdisplay=1.3.2
- redis-py=3.5.3
- s3fs=0.5.2
- selenium=3.141.0
- sentry-sdk=0.20.3
- tabulate=0.8.9
- tblib=1.6.0
- wget=1.20.1
- pip:
  - dataclasses-json==0.5.2
  - domain-utils==0.7.1
  - jsonschema==3.2.0
  - plyvel==1.3.0
name: openwpm
