channels:
    - conda-forge
dependencies:
    - black
    - codecov
    - pytest-cov
    - ipython
    - pip
    - pre-commit
    - pytest
    - mypy
    - pytest-asyncio
    - sphinx
    - recommonmark
    - sphinx-markdown-tables

